sourceCompatibility = 1.8
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.resources.srcDirs = ["../assets"]
sourceSets.test.java.srcDirs = [ "src/" ]
sourceSets.test.resources.srcDirs = ["../assets"]

project.ext.mainClassName = "com.mygdx.bomberman.DesktopLauncher"
project.ext.assetsDir = new File("../assets")

dependencies {
    // JUnit und Mockito
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.mockito:mockito-core:3.10.0'

    // LibGDX-Test-Abhängigkeiten
    testImplementation "com.badlogicgames.gdx:gdx-backend-headless:1.9.14"
    testImplementation "com.badlogicgames.gdx:gdx:1.9.14"
    testImplementation "com.badlogicgames.gdx:gdx-platform:1.9.14:natives-desktop"
    testImplementation "com.badlogicgames.gdx:gdx-box2d-platform:1.9.14:natives-desktop"
    testImplementation "com.badlogicgames.gdx:gdx-bullet-platform:1.9.14:natives-desktop"
    testImplementation "com.badlogicgames.gdx:gdx-backend-headless:1.9.14"

    // Additional dependencies
    testImplementation 'junit:junit:5.+'
    testImplementation 'org.mockito:mockito-core:3.11.2'
}

test {
    useJUnitPlatform()
}



eclipse.project.name = appName + "-core"
